# Common
spring:
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/temporary_project
      driver-class-name: org.mariadb.jdbc.Driver
      username: temp
      password: temp
logging:
  level:
    root: info
    playground:
      cheeseblossom:
        jpa: debug
    org:
      springframework:
        jdbc: trace
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
---
# local
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  config:
    activate:
      on-profile: local
---
# dev
spring:
  thymeleaf:
    cache: false
  config:
    activate:
      on-profile: dev
  web:
    resources:
      cache:
        period: 0